services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    command: ["poetry", "run", "uvicorn", "src.app:create_app", "--host", "0.0.0.0", "--port", "8000", "--reload",]
    restart: on-failure
    environment:
      - WATCHFILES_FORCE_POLLING=true

