[tool.poetry]
name = "tiny-grocery-store"
version = "0.1.0"
description = ""
authors = ["Juliana Machado <jfcaiado@hotmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.22.0"
fastapi = {extras = ["standard"], version = "^0.100.0"}
sqlmodel = "^0.0.8"
flet = "^0.8.2"
ipython = "^8.13.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
