[tool.poetry]
name = "tiny-grocery-store"
version = "0.1.0"
description = ""
authors = ["Juliana Machado <jfcaiado@hotmail.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.1"
sqlmodel = "^0.0.21"
uvicorn = "^0.30.3"
gunicorn = "^22.0.0"
pydantic-settings = "^2.1.0"
pytest = "^8.0.0"
psycopg2-binary = "^2.9.9"
flet = "^0.23.2"
uvloop = "^0.19.0"
httptools = "^0.6.1"
logfire = {extras = ["fastapi"], version = "^0.47.0"}
taskipy = "^1.13.0"
ruff = "^0.5.4"

[tool.poetry.group.dev.dependencies]
pytest-sugar = "^1.0.0"
ipython = "^8.20.0"
taskipy = "^1.12.2"
mypy = "^1.11.0"

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.taskipy.tasks]
install = 'poetry install'
lint = 'ruff check . && ruff check . --diff'
format = 'ruff check . --fix && ruff format .'
run = 'fastapi dev src/app.py'
pre_test = 'task lint'
test = 'pytest -s -x --cov=src -vv'
post_test = 'coverage html'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
